
classdef TimeMessage < ros.Message
    %TimeMessage MATLAB implementation of diff_drive_robot/TimeMessage
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'diff_drive_robot/TimeMessage' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c9570ee9192ab23fcd2f00225861bcac' % The MD5 Checksum of the message definition
        PropertyList = { 'Time' } % List of non-constant message properties
        ROSPropertyList = { 'time' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Time
    end
    methods
        function set.Time(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'TimeMessage', 'Time');
            obj.Time = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.diff_drive_robot.TimeMessage.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.diff_drive_robot.TimeMessage(strObj);
        end
    end
end
