// Generated by gencpp from file diff_drive_robot/TimeMessage.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_ROBOT_MESSAGE_TIMEMESSAGE_H
#define DIFF_DRIVE_ROBOT_MESSAGE_TIMEMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diff_drive_robot
{
template <class ContainerAllocator>
struct TimeMessage_
{
  typedef TimeMessage_<ContainerAllocator> Type;

  TimeMessage_()
    : time()  {
    }
  TimeMessage_(const ContainerAllocator& _alloc)
    : time(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::diff_drive_robot::TimeMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diff_drive_robot::TimeMessage_<ContainerAllocator> const> ConstPtr;

}; // struct TimeMessage_

typedef ::diff_drive_robot::TimeMessage_<std::allocator<void> > TimeMessage;

typedef boost::shared_ptr< ::diff_drive_robot::TimeMessage > TimeMessagePtr;
typedef boost::shared_ptr< ::diff_drive_robot::TimeMessage const> TimeMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diff_drive_robot::TimeMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diff_drive_robot::TimeMessage_<ContainerAllocator1> & lhs, const ::diff_drive_robot::TimeMessage_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diff_drive_robot::TimeMessage_<ContainerAllocator1> & lhs, const ::diff_drive_robot::TimeMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diff_drive_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_robot::TimeMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_robot::TimeMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_robot::TimeMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9570ee9192ab23fcd2f00225861bcac";
  }

  static const char* value(const ::diff_drive_robot::TimeMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9570ee9192ab23fULL;
  static const uint64_t static_value2 = 0xcd2f00225861bcacULL;
};

template<class ContainerAllocator>
struct DataType< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diff_drive_robot/TimeMessage";
  }

  static const char* value(const ::diff_drive_robot::TimeMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string time\n"
;
  }

  static const char* value(const ::diff_drive_robot::TimeMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diff_drive_robot::TimeMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diff_drive_robot::TimeMessage_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFF_DRIVE_ROBOT_MESSAGE_TIMEMESSAGE_H
